# Generated by Django 4.2.3 on 2023-08-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_details_created_by_alter_details_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='firstapp/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='details',
            old_name='is_deleted',
            new_name='item_deleted',
        ),
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='details',
            name='gmname',
            field=models.CharField(max_length=20, verbose_name='GM Name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='officename',
            field=models.CharField(max_length=20, verbose_name='Office Name'),
        ),
    ]
