# Generated by Django 4.2.3 on 2023-08-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_image_rename_is_deleted_details_item_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='item_deleted',
            new_name='is_deleted',
        ),
    ]
